function org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet(){var eb='',R=' top: -1000px;',nb='" for "gwt:onLoadErrorFn"',lb='" for "gwt:onPropertyErrorFn"',X='");',ob='#',Bb='.cache.js',qb='/',wb='//',zb='2153C785635D2024CE8B67EE7199E445',Ab=':',fb='::',S='<html><head><\/head><body><\/body><\/html>',ib='=',pb='?',kb='Bad handler "',V='Chrome',U='DOMContentLoaded',M='DUMMY',vb='base',tb='baseUrl',H='begin',N='body',G='bootstrap',sb='clear.cache.gif',hb='content',Db='end',W='eval("',I='gwt.codesvr.org.percepta.mgrankvi.floorplanner.gwt.AppWidgetSet=',J='gwt.codesvr=',mb='gwt:onLoadErrorFn',jb='gwt:onPropertyErrorFn',gb='gwt:property',ab='head',O='iframe',rb='img',Z='javascript',P='javascript:""',Cb='loadExternalRefs',bb='meta',_='moduleRequested',$='moduleStartup',cb='name',K='org.percepta.mgrankvi.floorplanner.gwt.AppWidgetSet',yb='org.percepta.mgrankvi.floorplanner.gwt.AppWidgetSet.devmode.js',ub='org.percepta.mgrankvi.floorplanner.gwt.AppWidgetSet.nocache.js',db='org.percepta.mgrankvi.floorplanner.gwt.AppWidgetSet::',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Y='script',xb='selectingPermutation',L='startup',T='undefined';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__sendStats=r;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__moduleName=K;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__errFn=null;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__moduleBase=M;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__softPermutationId=0;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__computePropValue=null;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__getPropMap=null;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__gwtInstallCode=function(){};org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==T){return typeof p.body!=T&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(U,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(U,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(V)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(W));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(X));g=f.createElement(Y);g.language=Z;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(Y);g.language=Z;g.text=c[i];e.appendChild(g);d(e,g)}}}
org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.onScriptDownloaded=function(a){l(function(){m(a)})};r($,_);var n=p.createElement(Y);n.src=k;p.getElementsByTagName(ab)[0].appendChild(n)}
org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__startLoadingFragment=function(a){return C(a)};org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(Y);c.language=Z;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(bb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(cb),k;if(j){j=j.replace(db,eb);if(j.indexOf(fb)>=0){continue}if(j==gb){k=i.getAttribute(hb);if(k){var l,m=k.indexOf(ib);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=eb}c[j]=l}}else if(j==jb){k=i.getAttribute(hb);if(k){try{d=eval(k)}catch(a){alert(kb+k+lb)}}}else if(j==mb){k=i.getAttribute(hb);if(k){try{e=eval(k)}catch(a){alert(kb+k+nb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(ob);if(b==-1){b=a.length}var c=a.indexOf(pb);if(c==-1){c=a.length}var d=a.lastIndexOf(qb,Math.min(c,b));return d>=0?a.substring(0,d+1):eb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(rb);b.src=a+sb;a=e(b.src)}return a}
function g(){var a=t(tb);if(a!=null){return a}return eb}
function h(){var a=p.getElementsByTagName(Y);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ub)!=-1){return e(a[b].src)}}return eb}
function i(){var a=p.getElementsByTagName(vb);if(a.length>0){return a[a.length-1].href}return eb}
function j(){var a=p.location;return a.href==a.protocol+wb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==eb){k=h()}if(k==eb){k=i()}if(k==eb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__moduleBase+a}
function D(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
s=function(a,b){return b in h[a]};org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__getPropMap=function(){var a={};for(var b in h){a[b]=j(b)}return a};org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__computePropValue=j;o.__gwt_activeModules[K].bindings=org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__getPropMap;r(G,xb);if(q()){return C(yb)}var k;try{k=zb;var l=k.indexOf(Ab);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__softPermutationId=g;return C(k+Bb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Cb,H);r(Cb,Db)}
A();org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__moduleBase=B();u[K].moduleBase=org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.__moduleBase;var F=D();E();r(G,Db);z(F);return true}
org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet.succeeded=org_percepta_mgrankvi_floorplanner_gwt_AppWidgetSet();